<?php

namespace Devflow\TelegramBot\Console\Commands;

use Devflow\TelegramBot\Console\Commands\Concerns\BootsProject;
use Devflow\TelegramBot\Console\Upgrades\UpgradeStep;

/**
 * Brings an existing project's scaffold up to date after a `composer update`
 * bumps the library version. Every step is independent and safe to re-run:
 * filesystem additions (a directory or file that doesn't exist yet) are
 * applied automatically since there's nothing to overwrite, while anything
 * that would mean editing a file the developer has almost certainly already
 * customized (bootstrap/app.php) is only ever reported, with the exact
 * snippet to paste in by hand — the same reasoning DoctorCommand uses for
 * read-only diagnostics, one step further.
 *
 * The checklist itself lives under Console/Upgrades/ — one file per version
 * (1.15.0.php, 1.16.0.php, ...), each returning a list of UpgradeStep. This
 * command just loads every file in version order and runs them uniformly.
 * There's no cutoff: a project on any older version runs the full history
 * and converges to the same end state, and each run states which library
 * version it checked up to. Shipping a new version that changes what a
 * scaffolded project needs means adding a file here — see AGENTS.md's
 * "Shipping a new version" note.
 */
class UpgradeCommand
{
    use BootsProject;

    private bool $dryRun = false;
    private int $applied = 0;
    private int $pending = 0;

    public function execute(array $args): void
    {
        foreach ($args as $arg) {
            if ($arg === '--dry-run') {
                $this->dryRun = true;
                continue;
            }

            $this->error("Unknown option: {$arg}");
            $this->line('  Usage: vendor/bin/devflow upgrade [--dry-run]');
            exit(1);
        }

        if (!$this->hasProjectBootstrap()) {
            $this->error('bootstrap/app.php not found. Run this command from your project root.');
            exit(1);
        }

        $steps = $this->loadSteps();
        $upToVersion = $steps === [] ? null : end($steps)['version'];

        echo "\n\033[1mdevflow upgrade\033[0m — checking this project's scaffold"
            . ($upToVersion !== null ? " against v{$upToVersion}" : '') . "\n\n";

        foreach ($steps as ['version' => $version, 'step' => $step]) {
            $this->runStep($version, $step);
        }

        $this->checkAiManifest();
        $this->summary();
    }

    /**
     * @return list<array{version: string, step: UpgradeStep}>
     */
    private function loadSteps(): array
    {
        $dir = dirname(__DIR__) . DIRECTORY_SEPARATOR . 'Upgrades';

        // Version files only (1.15.0.php, ...) — UpgradeStep.php itself
        // doesn't start with a digit, so it's never picked up here.
        $files = glob($dir . DIRECTORY_SEPARATOR . '[0-9]*.php') ?: [];

        usort($files, fn(string $a, string $b) => version_compare(basename($a, '.php'), basename($b, '.php')));

        $steps = [];
        foreach ($files as $file) {
            $version = basename($file, '.php');
            /** @var list<UpgradeStep> $fileSteps */
            $fileSteps = require $file;

            foreach ($fileSteps as $step) {
                $steps[] = ['version' => $version, 'step' => $step];
            }
        }

        return $steps;
    }

    private function runStep(string $version, UpgradeStep $step): void
    {
        if ($step->isNote()) {
            $this->line("  \033[36mi\033[0m [{$version}] {$step->okMessage}");
            return;
        }

        if ($step->isSatisfied($this->projectRoot())) {
            $this->pass("[{$version}] {$step->okMessage}");
            return;
        }

        if ($step->isFixable()) {
            $this->applyOrReport($version, $step->problemMessage, fn() => $step->apply($this->projectRoot()));
            return;
        }

        $this->pending++;
        $this->warn("[{$version}] {$step->problemMessage} — add by hand:");
        foreach (explode("\n", (string) $step->manualSnippet) as $line) {
            $this->line("        {$line}");
        }
    }

    /**
     * Always safe, so it isn't part of the applied/pending tally below: this
     * file is generated by reflection and never hand-edited, so refreshing
     * it is routine maintenance rather than a fix for something broken.
     */
    private function checkAiManifest(): void
    {
        if ($this->dryRun) {
            $this->line('  ~ .ai/api.json (skipped — dry run; would be regenerated)');
            return;
        }

        $result = (new AiManifestCommand())->writeTo($this->projectRoot());

        $result === null
            ? $this->warn('.ai/api.json could not be regenerated')
            : $this->pass(".ai/api.json regenerated ({$result})");
    }

    // ─── Helpers ────────────────────────────────────────────────────────────

    private function applyOrReport(string $version, string $description, callable $apply): void
    {
        if ($this->dryRun) {
            $this->warn("[{$version}] {$description} — would fix (dry run)");
            $this->pending++;
            return;
        }

        $apply();
        $this->success("[{$version}] Fixed: {$description}");
        $this->applied++;
    }

    // ─── Output ─────────────────────────────────────────────────────────────

    private function summary(): void
    {
        echo "\n";

        if ($this->applied === 0 && $this->pending === 0) {
            echo "\033[32m✓ Already up to date — nothing to do.\033[0m\n\n";
            return;
        }

        $parts = [];
        if ($this->applied > 0) {
            $parts[] = "\033[32m{$this->applied} fix(es) applied\033[0m";
        }
        if ($this->pending > 0) {
            $parts[] = "\033[33m{$this->pending} item(s) need manual attention\033[0m";
        }

        echo implode(', ', $parts) . "\n\n";

        if ($this->pending > 0) {
            $this->line('After making the manual changes above, run `vendor/bin/devflow doctor` to confirm everything still loads.');
        }

        $this->line('Schema changes (new columns/tables) ship as migrations — run `vendor/bin/devflow migrate` too.');
        echo "\n";
    }

    private function pass(string $msg): void
    {
        echo "  \033[32m✓\033[0m {$msg}\n";
    }

    private function warn(string $msg): void
    {
        echo "  \033[33m!\033[0m {$msg}\n";
    }

    private function success(string $msg): void
    {
        echo "  \033[32m✓\033[0m {$msg}\n";
    }

    private function line(string $msg): void
    {
        echo "{$msg}\n";
    }

    private function error(string $msg): void
    {
        echo "\033[31m✗\033[0m {$msg}\n";
    }
}
